### ISSUE TITLE
Add a way to disable `standard`

### ISSUE THREAD

**Issue by Yamakaky** [Olical/bastion#4]

**Comment by Olical** [comment]
I'll consider it. Maybe just a part of the configuration, like if your `standard` function in `bastion.conf.js` returns false or something. I'd rather not remove this since I want a set of defaults that you don't have to think about but give you a good base, but maybe giving the option to disable is a good idea.

Is this because you prefer a different linter?

**Comment by Yamakaky** [comment]
I just don't like the `standard` config ^^
While we are at it, it could be interesting to be able to choose he linter.

**Comment by Olical** [comment]
I'm afraid I'm going to close this. If you want to fork it and change the linter, be my guest. I just want a default set of tools that I use and know work well. It may not be for everyone, but I'm not really trying to cater for everyone. I apologise if this is a hindrance.
